### ISSUE TITLE
Will this work on Ubuntu Linux?

### ISSUE THREAD

**Issue by Parikshit01** [mkhorasani/maxon_python_windows_64#1]
Will this work on Ubuntu Linux?
I am getting the below error.
`lenevo@lenevo-M93p:~/maxon_python_windows_64$ python3 maxon_python_windows_64_example.py` 
`Traceback (most recent call last):`
`  File "maxon_python_windows_64_example.py", line 9, in <module>`
`    cdll.LoadLibrary(path)`
`  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary`
`    return self._dlltype(name)`
`  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__`
`    self._handle = _dlopen(self._name, mode)`
`OSError: /home/lenevo/maxon_python_windows_64\EposCmd64.dll: cannot open shared object file: No such file or directory`

**Comment by mkhorasani** [comment]
Hi @Parikshit01, I suspect it wouldn't work, the libraries were created for Windows OS.
